version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stock_alerts
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  authentication-service:
    build: ./services/authentication_service
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://user:password@postgres:5432/stock_alerts"

  stock-fetching-service:
    build: ./services/stock-fetching-service
    ports:
      - "8001:8001"
    depends_on:
      - kafka
      - redis

  stock-alert-service:
    build: ./services/stock-alert-service
    ports:
      - "8002:8002"
    depends_on:
      - kafka
      - postgres

  notification-service:
    build: ./services/notification-service
    ports:
      - "8003:8003"
    depends_on:
      - kafka

volumes:
  postgres_data:
